### ISSUE TITLE
The shadow effect is not working correctly with other window decorations.

### ISSUE THREAD

**Issue by SATYADAHAL** [matinlotfali/KDE-Rounded-Corners#120]
I don't clearly understand shadow size? When I increase its value it does not seem to increase width of shadow from window. It simply darkens it? In the   issue #101 I think , we need more shadow width to make it look more natural. And when the size of shadow increases by some number it gets sharp corner instead of circular.Is it bug or feature? I really don't get it.
![Screenshot_20231215_152153](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/1d92376d-49d5-4ec6-a855-3a9cf5eb5626)

**Comment by matinlotfali** [comment]
Let me see if I can reproduce it and I will get back to you

**Comment by SATYADAHAL** [comment]
> Let me see if I can reproduce it and I will get back to you

I am on fedora 39 with following specs.
![Screenshot_20231216_061633](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/49ece62e-4643-4426-8ed1-d48cef0218a4)

**Comment by matinlotfali** [comment]
Can't reproduce in Fedora 39 X11. So I guess there is another effect or decoration that is at fault.
![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/7337168/68c02ca1-9168-405b-985e-8ae45e2621cb)

**Comment by SATYADAHAL** [comment]
@matinlotfali I figured it out. It was due to window decoration. When i use window decorations which had transparency the problem was there. In the image below its "sweet-dark" window decoration. 
![Screenshot_20231217_145926](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/3c7d6507-8c56-48c8-9d69-60d1b0b74635)

But with solid window decoration I had no problem.
![Screenshot_20231217_150010](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/51309409/d4b285f5-d9ed-49b9-ad59-5d77519e893d)

And with window decoration called "Plastik" there was no shadow at all.

**Comment by matinlotfali** [comment]
Okay, I rephrased the issue to look into it.

**Comment by matinlotfali** [comment]
Okay, I confirm that I can reproduce the issue and I can provide some explanation as to what is happening.

Each window decoration defines some extra space to draw their shadows (expandedGeometry). My effect, as it needs shadows around corners and decorations don't draw their shadows at corners, I render my own version of shadow.
However, I am not checking how much space is specified by the decoration (I assumed they all have plenty of space). So On large shadow size, you see that the render is cut off because of the decoration's limited expandedGeometry. In ("plastik" decoration, for example, there is no expandedGeometry at all.)

You can see in the screenshot that the window at the front has a big shadow size (ugly) and the window at the back has a small one (nice).

So either the user should adjust the shadow size or **I need to prevent users from using a number higher than the expanded Geometry and assume the largest possible depending on the decoration they use.**

![image](https://github.com/matinlotfali/KDE-Rounded-Corners/assets/7337168/a6f9fb27-5947-4a82-8ebc-bc4c3b7d0de6)

**Comment by matinlotfali** [comment]
@SATYADAHAL The pull request #122 sets a limit to the shadow size depending on the decoration you choose. Please tell me what you think about it.

**Comment by RomanKode** [comment]
> @SATYADAHAL The pull request #122 sets a limit to the shadow size depending on the decoration you choose. Please tell me what you think about it.

Is there a reason why some apps(in my case, steam) does not render shadows?

**Comment by matinlotfali** [comment]
@SATYADAHAL KWin is not providing any `expandedGeometry` around the decoration of some apps like Steam to allow me to render any shadows. And I don't know any way to force KWin for this.

**Comment by matinlotfali** [comment]
I found this hack:

In [ System settings ] -> [ Window management ] -> [ Window rules ] -> [ Appearance & Fixes ] , set [ No titlebar ] and frame to No

In [ System settings ] -> [ Application Style ] -> [ Window decoration ] -> [ Breeze theme setting ] -> [ Window specific overrides ], Set [ border size ] to No border size and set [ Hide Window title bar ] to yes.

After that, STEAM window gets its shadows back.

**Comment by matinlotfali** [comment]
I will add this to `README.md`
