### ISSUE TITLE
CMake Error at CMakeLists.txt:25 (find_package):

### ISSUE THREAD

**Issue by hrqmonteiro** [matinlotfali/KDE-Rounded-Corners#132]
```
CMake Error at CMakeLists.txt:25 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.240.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.113.0



-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

```

**Comment by matinlotfali** [comment]
Looks like it is choosing version 240 instead of 113 because it detects qt6 in this line:

https://github.com/matinlotfali/KDE-Rounded-Corners/blob/a1c3b829cd255df95d01d1416cd427de5ce752ac/CMakeLists.txt#L7-L14

I need to change the code to manage this switch without Qt

Note that you can still use the release [v0.5.0](https://github.com/matinlotfali/KDE-Rounded-Corners/releases/tag/v0.5.0)

**Comment by matinlotfali** [comment]
I think #133 should fix the issue. 

@hrqmonteiro  Can you test it for me?
