### ISSUE TITLE
Rounded Corners do not appear when taking a screenshot of a window

### ISSUE THREAD

**Issue by rdrms** [matinlotfali/KDE-Rounded-Corners#15]
Sorry for doing TWO issues on this small repository within 10 minutes, but I just noticed something else!

When using Meta+PrScr (I believe this is the default hotkey, at least on KDE neon), to take a screenshot of a single window, the rounded corners do not appear.  Again, this may be unavoidable, but I wanted to let you guys know.

Here's a couple images, first is taken with WinKey+PrintScreen to capture just the window, shadows, and a bit of white space.
The second is a cropped image of a screenshot of my whole desktop, showing the window with rounded corners as intended.
As you can see although the current Breeze window decorations on KDE neon are rounded at the top, the bottom is not rounded as it appears in the second screenshot.

![Screenshot_20211120_114716](https://user-images.githubusercontent.com/2936638/142738192-4a766afa-b456-4013-969f-179b96022300.png)
![Screenshot_20211120_120500](https://user-images.githubusercontent.com/2936638/142738197-9ef6c209-3082-49d7-a213-ddbfd7020f11.png)
.

**Comment by matinlotfali** [comment]
I guess Win+PrintScreen captures windows without any desktop effects. Do you know any other desktop effect that you could try to capture with this approach to test my hypothesis?

**Comment by ryanrms** [comment]
I'm not really sure, I have been using a different desktop which uses Kwin (called Cutefish).  It uses a plugin called "RoundedWindow" to achieve the same effect.  I'm not sure if it would show in a regular screenshot of the window, because it doesn't include KDE screenshot in the desktop.

Oh, I installed it, and it appears that this one does show the rounded corners when Spectacle (KDE screenshot tool) is used.  It also doesn't have the issues with the wobbly windows that  KDE-Rounded-Corners does.  


![rounded corners](https://user-images.githubusercontent.com/2936638/143955484-13d1a333-ce26-486a-bc31-ccf9ec531889.png)


The code may be found here:
https://github.com/cutefishos/kwin-plugins/tree/main/plugins/roundedwindow

Sorry, not trying to shill another solution on your issue tracker, just wanted to let you know.

**Comment by matinlotfali** [comment]
Thanks for letting me know. I will definitely check the cutefish codes. Let's keep this issue open so that I can provide updates for everyone.

**Comment by Hibanaw** [comment]
> Thanks for letting me know. I will definitely check the cutefish codes. Let's keep this issue open so that I can provide updates for everyone.

Excuse me, I've tried to compile and install the cutefish's kwin-plugin under KDE Plasma on Manjaro(based on archlinux), but no rounded window effect appears. I wonder if it works well for you.

**Comment by a-parhom** [comment]
Cutefish's implementation was initially based on ShapeCorners code, but now it is rewritten and depends on highly customized fork of KWin, so it isn't compatible with vanilla KWin from KDE Plasma any more.
If Cutefish's changes could be backported to upstream KWin, that would fix many bugs, including "korners" and cut out shadows.

**Comment by matinlotfali** [comment]
> > Thanks for letting me know. I will definitely check the cutefish codes. Let's keep this issue open so that I can provide updates for everyone.
> 
> Excuse me, I've tried to compile and install the cutefish's kwin-plugin under KDE Plasma on Manjaro(based on archlinux), but no rounded window effect appears. I wonder if it works well for you.

Doesn't work for me either. As @a-parhom it is not compatible with vanilla KWin. I am closing this issue.
