### ISSUE TITLE
Disable Roundness on Tile/Maximize

### ISSUE THREAD

**Issue by Ruby-Haruko** [matinlotfali/KDE-Rounded-Corners#176]
Exist a Solution to seperate this option for only Tiled windows? In Chrome the fullscreen videos have the roundness, too

**Comment by Jas-SinghFSU** [comment]
This would be super awesome. I have Bismuth on my KDE Plasma and this tool is downright amazing for rounding corners and adding borders to active windows. The only downside is, if I maximize a window it still shows the border which sucks if you're watching full-screen youtube videos and such since it adds a border.

**Comment by matinlotfali** [comment]
Fixed in #93
