### ISSUE TITLE
[KWin 5.24] The shadow beneath the rounded corner is gone

### ISSUE THREAD

**Issue by matinlotfali** [matinlotfali/KDE-Rounded-Corners#2]
As can be seen in the screenshot, the shadow below the rounded corners is missing.
![Screenshot_20211024_010159](https://user-images.githubusercontent.com/7337168/138585772-a20930e6-bdc4-452f-b541-9c7bc5c5e224.png)
Currently in contact with KWin developers to be able to draw a shadow in that specific spot manually.

**Comment by a-parhom** [comment]
Eventually I have managed to deal with this corners problem in [this commit](https://github.com/a-parhom/LightlyShaders/commit/5e08eb3439dad848bcf01f393f3d3af0bcd61270) in my fork. It uses the new DeformEffect approach from Plasma 5.23. Also it shrinks the shadow a little bit (the bigger is your corner radius the more it shrinks the shadow), because now there is no such thing as WindowQuadType so no way to decouple the shadows from the window frame. So I have to squeeze the shadows to the center in order to hide cut out corners. On the other hand, it works well with client-side decoration shadows, like Firefox or Chrome (well used without system decoration). Not a perfect solution, but no more blur/shadow bug. Maybe someone will make a better solution based on this approach.

**Comment by a-parhom** [comment]
Actually, I now have an idea how to deal with this without getting shadows smaller. I'll try that today or in a few days and if it will work, I'll push it to my repo.

**Comment by ryu-ketsueki** [comment]
> Eventually I have managed to deal with this corners problem in [this commit](https://github.com/a-parhom/LightlyShaders/commit/5e08eb3439dad848bcf01f393f3d3af0bcd61270) in my fork. It uses the new DeformEffect approach from Plasma 5.23. Also it shrinks the shadow a little bit (the bigger is your corner radius the more it shrinks the shadow), because now there is no such thing as WindowQuadType so no way to decouple the shadows from the window frame. So I have to squeeze the shadows to the center in order to hide cut out corners. On the other hand, it works well with client-side decoration shadows, like Firefox or Chrome (when used without system decoration). Not a perfect solution, but no more blur/shadow bug. Maybe someone will make a better solution based on this approach.

Sending this here because your fork of LightlyShaders doesn't have issue reporting.
![Flameshot_202111 4_120431](https://user-images.githubusercontent.com/39316730/140339374-5719c540-9bc3-477c-87e5-965ed1055177.png)

There must be a bug with how the bottom shadows are handled. They keep increasing in size instead of shrinking. Corner roundness are at 8px for me since it's the max Lightly allows.

**Comment by a-parhom** [comment]
I can see, that the corners on your screenshot are also cut out, which is wrong. I use this with Kvantum, not Lightly and don't have those issues. I'm pretty sure, that my approach can have bugs, because I'm not very experienced in KWin, Qt and C++ (I'm a web-developer), but I'll look into this issues and try to find solution as soon as I have time. Maybe, a couple of days. But no guarantee that I'll find it :-)

**Comment by a-parhom** [comment]
From the screenshot it seems that with Lightly the frameGeometry and expandedGeomerty return wrong values (well, not the ones my deform function is expecting). And I can't say anything for now about the Slide effect, I'll have to test it on my machine. As I said, in a couple of days, I think.

**Comment by a-parhom** [comment]
> There must be a bug with how the bottom shadows are handled. They keep increasing in size instead of shrinking. Corner roundness are at 8px for me since it's the max Lightly allows.
> 
> I also realized that it broke the "Slide" Virtual Desktop Switching Animation. The windows don't slide with the desktops anymore

Please, try [this commit](https://github.com/a-parhom/LightlyShaders/commit/76fb7e14267ad17516779a1d94711c65976528eb), it should fix your issues.

P.S. I also enabled the Issues section in my repo, so you can open an issue there if there is one.

**Comment by ryu-ketsueki** [comment]
> > There must be a bug with how the bottom shadows are handled. They keep increasing in size instead of shrinking. Corner roundness are at 8px for me since it's the max Lightly allows.
> > I also realized that it broke the "Slide" Virtual Desktop Switching Animation. The windows don't slide with the desktops anymore
> 
> Please, try [this commit](https://github.com/a-parhom/LightlyShaders/commit/76fb7e14267ad17516779a1d94711c65976528eb), it should fix your issues.
> 
> P.S. I also enabled the Issues section in my repo, so you can open an issue there if there is one.

So far seem to have been resolved. I'll be reporting any bugs I find if there are any

**Comment by matinlotfali** [comment]
@a-parhom thank you for your effort. but I think your approach is resource intensive. You are painting windows twice, one smaller shadow for shadow and one for the actual window. With 10 unmaximized windows open on the dual monitor, it can reduce my desktop FPS from 60 to 30.
I think we can get better performance by drawing our own shadows and ignoring the native shadow of KWin.

**Comment by a-parhom** [comment]
I've implemented entirely different approach. It now tries to kind of interpolate the shadows. Although, can't tell it's absolutely perfect, but it works for me in most cases.

**Comment by TobiPeterG** [comment]
A fix for the korners bug lands in Plasma 5.25, will that in turn fix this issue here as well?

**Comment by a-parhom** [comment]
No, it won't. This bug has another cause.

**Comment by matinlotfali** [comment]
The issue has changed into a different issue in the new KWin 5.25. See #37

**Comment by matinlotfali** [comment]
Please look at merge request #44 and try it out.
It needs more testing before I merge it into the master branch and close this issue.
