### ISSUE TITLE
[Feature request] Arbitrary shaders

### ISSUE THREAD

**Issue by parkerlreed** [matinlotfali/KDE-Rounded-Corners#66]
3 years ago I had the idea of using the RetroArch GLSL shaders to apply a CRT effect to the entire desktop. 

https://www.reddit.com/r/kde/comments/acbjfk

I created an example video with a screen recording playing through RetroArch's FFmpeg core (The compression kills it but there are fine lines across the screen)

https://youtu.be/-M404wqfmTM

Would be great to have this as possibility for the desktop effects. 

The actual shaders are located here

https://github.com/libretro/glsl-shaders/tree/master/crt

**Comment by matinlotfali** [comment]
This seems to be not a "feature request" but rather a "project request" because it is a screen effect, not a window effect.
Honestly, I don't feel motivated enough to implement it. But I might be able to provide you with some hints from other KWinEffects such as this one to implement it yourself:
https://github.com/KDE/kwin/tree/master/src/effects/invert

If you have further questions please send me an email instead.
