### ISSUE TITLE
[KWin 5.27] shader property is dropped from WindowPaintData

### ISSUE THREAD

**Issue by matinlotfali** [matinlotfali/KDE-Rounded-Corners#68]
My implementation of **KDE-Rounded-Corners** relies on the `shader` property in the `WindowPaintData` class in which I inject my custom shader.
Recently, the `shader` property has been dropped in this [kwin commit](https://github.com/KDE/kwin/commit/3aa635430bc67abd4d1a721153b9969b929ec57d) by @zzag. This is causing compile errors on the latest **KDE Neon Unstable** release.

    void
    ShapeCornersEffect::drawWindow(KWin::EffectWindow *w, int mask, const QRegion& region, KWin::WindowPaintData &data)
    {    
        .
        .
        auto &shader = m_shaderManager.Bind(w, m_config);
        data.shader = shader.get();         <--------------------------- This assignment fails!
        glActiveTexture(GL_TEXTURE1);
        m_managed[w]->bind();
        glActiveTexture(GL_TEXTURE0);
        KWin::effects->drawWindow(w, mask, region, data);
        m_managed[w]->unbind();
        m_shaderManager.Unbind();
    }

As suggested in the commit message, I tried to port the effect to the `OffscreenEffect` and use the `setShader` function. However, after studying [changes in the invert effect](https://github.com/KDE/kwin/commit/4363b25b2df494789a6452e4241e5437df17edbf), I noticed that I shouldn't be using the `drawWindow` function anymore and therefore, I can not bind my textures and variables.

**Comment by bluee111** [comment]
Hello friend, I love your work on Rounded Corners and I want to clarify that I am not a programmer, but I asked ChatGPT your question and this answered me: I hope it helps you

A possible solution to this problem could be to use a different rendering function instead of drawWindow. For example, you could use the render function, which is responsible for drawing the content of the window in the OpenGL context.

Another possibility is to use a custom rendering function, which takes care of drawing the window content in the OpenGL context. This function can be defined in the effect's source code file and can be used to bind the necessary textures and variables.
